"""Shared constants across the project."""

FEATURES_ORDER = [
    "VHM0",
    "WSPD",
    "VTM02",
    "U10",
    "V10",
    "wind_dir_sin",
    "wind_dir_cos",
    "wave_dir_sin",
    "wave_dir_cos",
    "cos_delta",
    "sin_delta",
    "alongwind",
    "crosswind",
    "storm_regime",
    "storm_regime_sig",
    "sin_hour",
    "cos_hour",
    "sin_doy",
    "cos_doy",
    "sin_month",
    "cos_month",
    "lat_norm",
    "lon_norm",
    "corrected_VHM0",
    "corrected_VTM02",
]
